### ISSUE TITLE
Rake task to copy config files

### ISSUE THREAD

**Issue by katafrakt** [samuelsimoes/hanami-webpack#1]
Hi, @samuelsimoes!

Following the discussion on Gitter, I investigated a little bit whether it would be possible or not to have dynamically loaded rake task to create default configuration. Turns out it's probably not possible. I know we are all used to Rails' ecosystem and how it scans all the load path in search of possible rake tasks, but this comes with a performance cost and I think this is not a "Hanami-way", so it won't be introduces in any near future.

Alternatively, the README could ask the user to manually include in his `Rakefile` a line like this:

``` ruby
require 'hanami_webpack/tasks'
```

This would expose the tasks from a file in `hanami-webpack` gem to Hanami project, for example aforementioned task to copy default config.

How do you feel about solution like that? I know it is far from perfect but is the best thing I could come up with about this.

**Comment by samuelsimoes** [comment]
I really appreciate your help, but I wanted to make an automatic process. But while my case just needs one task, there's no much problem in ask user to copy two files on your project folder. I just needed some sort of confirmation that it's actually "impossible". I will remove that to-do from README.

Thanks for your attention. 😀
