### ISSUE TITLE
Add host option to webpack dev server binary

### ISSUE THREAD

**Issue by charlie-wasp** [samuelsimoes/hanami-webpack#4]
Hello!

How about to add `--host` option to `webpack-dev-server` invocation?

My use case is that I run hanami application in Docker, so I need to specify `--host=0.0.0.0` to make webpack dev server available for my web browser

**Comment by samuelsimoes** [comment]
Hi, @charlie-wasp 

This is indeed necessary and the best way to do this would be through ENV vars. I will get this in this weekend, but a PR is very welcome. 👍

**Comment by charlie-wasp** [comment]
Allright, I will try to implement this :+1:

**Comment by samuelsimoes** [comment]
Closing since we discussed it at https://github.com/samuelsimoes/hanami-webpack/pull/5.
